// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // O CLI (migrate/introspect) precisa de uma conexão direta ao Postgres, não da
    // conexão via pooler (pgbouncer) usada em runtime. Na Supabase, DIRECT_URL é a
    // porta 5432 (conexão direta); DATABASE_URL é a porta 6543 (pooler, transaction
    // mode) usada pelo app em src/lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
